services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/isainz-r/Volumenes/MD
      o: bind
    name: mariadb_data

networks:
  inception:
    driver: bridge
